apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"nsupdate-operator","namespace":"kube-system"},"spec":{"containers":[{"image":"localhost:5000/nsupdate-operator:1.0.0","imagePullPolicy":"Always","name":"nsupdate-operator"}],"serviceAccountName":"nsupdate-operator"}}
  creationTimestamp: "2023-09-17T16:44:48Z"
  name: nsupdate-operator
  namespace: kube-system
  resourceVersion: "13511"
  uid: 5345cdf7-2087-413a-b059-9beba3a05869
spec:
  containers:
  - image: localhost:5000/nsupdate-operator:1.0.0
    imagePullPolicy: Always
    name: nsupdate-operator
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xjw8d
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: nsupdate-operator
  serviceAccountName: nsupdate-operator
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-xjw8d
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-09-17T16:44:48Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-09-17T16:44:49Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-09-17T16:44:49Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-09-17T16:44:48Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0eaad2c7e0ad3042f8630b213e29bfb57cd0c67dfe1bea15b4686941a38ab6cb
    image: localhost:5000/nsupdate-operator:1.0.0
    imageID: docker-pullable://localhost:5000/nsupdate-operator@sha256:3bacf6319f312b5ec2f3f259c4c2cd87cddf5b107eaee04859150ff876c040ea
    lastState: {}
    name: nsupdate-operator
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-09-17T16:44:49Z"
  hostIP: 192.168.59.158
  phase: Running
  podIP: 172.17.0.6
  podIPs:
  - ip: 172.17.0.6
  qosClass: BestEffort
  startTime: "2023-09-17T16:44:48Z"