---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsupdate-operator
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nsupdate-operator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nsupdate-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nsupdate-operator
subjects:
  - kind: ServiceAccount
    name: nsupdate-operator
    namespace: kube-system
